// ─────────────────────────────────────────────────────────────────────────────
// AutoCAD Visual Styles Definitions
// ─────────────────────────────────────────────────────────────────────────────

export const VISUAL_STYLES = {
  shaded_edges: {
    id: 'shaded_edges',
    name: 'Shaded with Edges',
    shortName: 'Shaded+Edges',
    desc: 'AutoCAD standard solid with crisp feature edge contour lines',
    showEdges: true,
    wireframe: false,
    opacity: 1.0,
    transparent: false,
  },
  realistic: {
    id: 'realistic',
    name: 'Realistic PBR',
    shortName: 'Realistic',
    desc: 'Smooth PBR CAD material with ambient occlusion and specular reflections',
    showEdges: false,
    wireframe: false,
    opacity: 1.0,
    transparent: false,
  },
  conceptual: {
    id: 'conceptual',
    name: 'Conceptual',
    shortName: 'Conceptual',
    desc: 'AutoCAD warm-cool duotone surface curvature visualization',
    showEdges: true,
    wireframe: false,
    opacity: 1.0,
    transparent: false,
    tint: '#94A3B8',
  },
  xray: {
    id: 'xray',
    name: 'X-Ray (Ghosted)',
    shortName: 'X-Ray',
    desc: 'Semi-translucent solid revealing internal bores, holes, and cavities',
    showEdges: true,
    wireframe: false,
    opacity: 0.45,
    transparent: true,
  },
  wireframe: {
    id: 'wireframe',
    name: '3D Wireframe',
    shortName: 'Wireframe',
    desc: 'Pure technical wireframe contour lines',
    showEdges: true,
    wireframe: true,
    opacity: 1.0,
    transparent: false,
  },
};

export const VIEWPORT_BACKGROUNDS = {
  autocad_dark: {
    id: 'autocad_dark',
    name: 'AutoCAD 3D Dark',
    topColor: '#242A35',
    bottomColor: '#12151B',
    gridCellColor: '#1E2530',
    gridSectionColor: '#2D3748',
    axesColor: '#475569',
    edgeColor: '#0B0F19',
  },
  classic_charcoal: {
    id: 'classic_charcoal',
    name: 'Classic Charcoal',
    topColor: '#1A1D24',
    bottomColor: '#0B0D10',
    gridCellColor: '#14181E',
    gridSectionColor: '#222832',
    axesColor: '#3B4452',
    edgeColor: '#020406',
  },
  blueprint: {
    id: 'blueprint',
    name: 'Engineering Blueprint',
    topColor: '#0B2347',
    bottomColor: '#030D1C',
    gridCellColor: '#0F305C',
    gridSectionColor: '#1D4E89',
    axesColor: '#38BDF8',
    edgeColor: '#020A16',
  },
  atelier_sand: {
    id: 'atelier_sand',
    name: 'Atelier Warm Sand',
    topColor: '#F6F6F0',
    bottomColor: '#E8E5DD',
    gridCellColor: '#D8D4CA',
    gridSectionColor: '#B5B0A2',
    axesColor: '#8C8578',
    edgeColor: '#474040',
  },
  drafting_light: {
    id: 'drafting_light',
    name: 'Light Drafting',
    topColor: '#EAEFF5',
    bottomColor: '#CBD5E1',
    gridCellColor: '#CBD5E1',
    gridSectionColor: '#94A3B8',
    axesColor: '#64748B',
    edgeColor: '#1E293B',
  },
};
